version: "3.8"

networks:
  monitor-net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  # ====================================================================================================
  #     Public services
  # ====================================================================================================
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/src:/app/backend/src
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "backend"

  # ====================================================================================================
  #     Monitoring services
  # ====================================================================================================
  # Metric visualize
  grafana:
    image: grafana/grafana:7.3.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:80/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  # Metrix data base
  prometheus:
    image: prom/prometheus:v2.23.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  # Push acceptor for ephemeral and batch jobs
  pushgateway:
    image: prom/pushgateway:v1.3.0
    container_name: pushgateway
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  # Alert management
  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  # ====================================================================================================
  #     Metrics collector
  # ====================================================================================================
  # Nginx metrics collector
  nginxexporter:
    image: fish/nginx-exporter
    container_name: nginxexporter
    command:
      - "-nginx.scrape_uri=http://nginx:9113/"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  # Hardware and OS metrics collector
  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  # Container metric collector
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  # ====================================================================================================
  #     Proxy
  # ====================================================================================================
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "9090:9090" # prometheus
      - "9091:9091" # push gateway
      - "9093:9093" # Alert management
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/htpassword:/etc/nginx/conf.d/htpassword
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "proxying"
